### PR TITLE
Added some types to function declarations

### PR DESCRIPTION
**Pull request by module17**
Looks right.

### CODE REVIEW

**Comment by cogspace** [comment]
Justification?

**Comment by module17** [comment]
`agency` can only be a string.

**Comment by cogspace** [comment]
That's true but "a, b string" is the same as "a string, b string" in Go. Why the repetition? The compiler still checks it correctly.

—

**Comment by module17** [comment]
You're right. Thought it would be friendlier for humans and `godoc` perhaps.

**Pull request closed without merging**
